# Generated by Django 2.2.16 on 2022-08-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0003_remove_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=1, upload_to='recipe/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
