# Generated by Django 2.2.16 on 2022-08-21 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodgram', '0006_auto_20220819_2141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourites',
            new_name='Favorite',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipeingredient', to='foodgram.Ingredient', verbose_name='Название ингредиента'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipeingredient', to='foodgram.Recipe', verbose_name='Название рецепта'),
        ),
    ]
